### ISSUE TITLE
Error al cargar nueva semilla.

### ISSUE THREAD

**Issue by andreadruiz** [gcoop-libre/bioleft#36]
Al agregar una nueva semilla, tengo este error con la version 8.7.10 de drupal core. 

```
[Wed Nov 27 17:58:12 2019] Error: Class 'Drupal\views\Plugin\EntityReferenceSelection\Xss' not found in /var/www/html/bioleft/core/modules/views/src/Plugin/EntityReferenceSelection/ViewsSelection.php on line 269 #0 /var/www/html/bioleft/core/modules/views/src/Plugin/EntityReferenceSelection/ViewsSelection.php(224): Drupal\views\Plugin\EntityReferenceSelection\ViewsSelection->stripAnchorTagsFromResults(Array)
#1 /var/www/html/bioleft/core/lib/Drupal/Core/Field/Plugin/Field/FieldType/EntityReferenceItem.php(600): Drupal\views\Plugin\EntityReferenceSelection\ViewsSelection->getReferenceableEntities()
#2 /var/www/html/bioleft/core/lib/Drupal/Core/Field/Plugin/Field/FieldWidget/OptionsWidgetBase.php(116): Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem->getSettableOptions(Object(Drupal\Core\Session\AccountProxy))
#3 /var/www/html/bioleft/modules/contrib/entity_reference_views_select/src/Plugin/Field/FieldWidget/EntityReferenceViewsOptionsButtonsWidget.php(82): Drupal\Core\Field\Plugin\Field\FieldWidget\OptionsWidgetBase->getOptions(Object(Drupal\bioleft_semilla\Entity\Semilla))
#4 /var/www/html/bioleft/core/lib/Drupal/Core/Field/WidgetBase.php(335): Drupal\entity_reference_views_select\Plugin\Field\FieldWidget\EntityReferenceViewsOptionsButtonsWidget->formElement(Object(Drupal\Core\Field\EntityReferenceFieldItemList), 0, Array, Array, Object(Drupal\Core\Form\FormState))
#5 /var/www/html/bioleft/core/lib/Drupal/Core/Field/WidgetBase.php(85): Drupal\Core\Field\WidgetBase->formSingleElement(Object(Drupal\Core\Field\EntityReferenceFieldItemList), 0, Array, Array, Object(Drupal\Core\Form\FormState))
#6 /var/www/html/bioleft/core/lib/Drupal/Core/Entity/Entity/EntityFormDisplay.php(177): Drupal\Core\Field\WidgetBase->form(Object(Drupal\Core\Field\EntityReferenceFieldItemList), Array, Object(Drupal\Core\Form\FormState))
#7 /var/www/html/bioleft/core/lib/Drupal/Core/Entity/ContentEntityForm.php(125): Drupal\Core\Entity\Entity\EntityFormDisplay->buildForm(Object(Drupal\bioleft_semilla\Entity\Semilla), Array, Object(Drupal\Core\Form\FormState))
#8 /var/www/html/bioleft/core/lib/Drupal/Core/Entity/EntityForm.php(117): Drupal\Core\Entity\ContentEntityForm->form(Array, Object(Drupal\Core\Form\FormState))
#9 /var/www/html/bioleft/modules/custom/bioleft_semilla/src/Form/SemillaForm.php(62): Drupal\Core\Entity\EntityForm->buildForm(Array, Object(Drupal\Core\Form\FormState))
#10 [internal function]: Drupal\bioleft_semilla\Form\SemillaForm->buildForm(Array, Object(Drupal\Core\Form\FormState))
#11 /var/www/html/bioleft/core/lib/Drupal/Core/Form/FormBuilder.php(519): call_user_func_array(Array, Array)
#12 /var/www/html/bioleft/core/lib/Drupal/Core/Form/FormBuilder.php(276): Drupal\Core\Form\FormBuilder->retrieveForm('semilla_mis_sem...', Object(Drupal\Core\Form\FormState))
#13 /var/www/html/bioleft/core/lib/Drupal/Core/Controller/FormController.php(93): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\bioleft_semilla\Form\SemillaForm), Object(Drupal\Core\Form\FormState))
#14 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#15 /var/www/html/bioleft/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#16 /var/www/html/bioleft/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#17 /var/www/html/bioleft/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#18 /var/www/html/bioleft/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#19 /var/www/html/bioleft/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#20 /var/www/html/bioleft/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#21 /var/www/html/bioleft/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /var/www/html/bioleft/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /var/www/html/bioleft/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 /var/www/html/bioleft/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 /var/www/html/bioleft/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#26 /var/www/html/bioleft/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#27 /var/www/html/bioleft/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 /var/www/html/bioleft/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#29 /var/www/html/bioleft/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#30 /var/www/html/bioleft/vendor/drush/drush/misc/d8-rs-router.php(46): require('/var/www/html/b...')
#31 {main}

```

**Comment by andreadruiz** [comment]
Apliqué este parche https://www.drupal.org/project/drupal/issues/2174633 y con eso se solucionó el problema. 
En este [link](https://www.drupal.org/project/drupal/issues/2174633#comment-12518942) hay más info.
